---
title: "fig 1 Histone methylation drives the structure of the rice root microbiota"
author: "Dairui"
date: "2021/6/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# Clean workspace
rm(list=ls()) 
# Load setting and functions
source("../script/stat_plot_functions.R")
# Set output directory
output_dir="./"
```


## A. Constrained principal coordinates analysis of root samples.
```{r}
# input files:
design = read.table("../data/design.txt", header=T, row.names=1, sep="\t",stringsAsFactors = F)
beta = read.table(paste("../data/asvtab_norm.txt",sep=""), header=T, row.names=1, sep="\t", comment.char="") 

# reorder the groups:
design$variety = factor(design$variety,levels = c("Bulksoil", "Wildtype", "Mutant"))
design$group = design$genotype
design$group = factor(design$group, levels = c("DJ-WT","DJ-jmj703","ZH11-WT","ZH11-sdg714","Nip-WT","Nip-dcl3a-1","Nip-dcl3a-3","Bulksoil"))

# filter samples, only keep the root:
sub_design = subset(design, compartment %in% c("Root"))
idx = rownames(sub_design) %in% colnames(beta)
sub_design=sub_design[idx,]
sub_beta=beta[,rownames(sub_design)]

asvtab = t(sub_beta)
  
# Constrained analysis ASV table by genotype
capscale.gen = capscale(asvtab ~ group, data=sub_design, add=F, sqrt.dist=T, distance= "bray") 
# ANOVA-like permutation analysis
perm_anova.gen = anova.cca(capscale.gen, permutations = 1000, parallel = 9)
  
# generate variability tables and calculate confidence intervals for the variance
var_tbl.gen = variability_table(capscale.gen)
eig = capscale.gen$CCA$eig
variance = var_tbl.gen["constrained", "proportion"]
p.val = perm_anova.gen[1,4]
  
# extract the weighted average (sample) scores
points = capscale.gen$CCA$wa[, 1:2]
points = as.data.frame(points)
points = cbind(points, sub_design)
colnames(points)[1:2] = c("PC1", "PC2")

write.table(points[,c(1,2,7,8,18)], "points_coordinates_for_CPCoA.txt", sep = "\t", quote = F, row.names = T, col.names = T )
write.table(var_tbl.gen, "variance_for_CPCoA.txt", sep = "\t", quote = F, row.names = T, col.names = T )
  
# plot PC 1 and 2
p = ggplot(points, aes(x=PC1, y=PC2, color=group, shape = variety)) + geom_point(alpha=.9, size=2) +
    geom_hline(yintercept = 0, linetype="solid", color = "grey") +
    geom_vline(xintercept = 0,linetype="solid", color = "grey") +
    scale_color_manual(values = c("#60a3bc","#82ccdd","#b71540","#e55039","#e58e26","#fa983a","#f6b93b")) +
    scale_shape_manual(values = c(19,8))+
    labs(x=paste("CPCo 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
         y=paste("CPCo 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep="")) + 
    ggtitle(paste(format(100 * variance, digits=3), " % of variance; p=",format(p.val, digits=2),sep="")) + 
    theme_bw() + main_theme
  
  if (TRUE){
    p = p + stat_ellipse(level=0.68)
  }
p

# save figures
ggsave("CPCoA_of_Root_1A.pdf", p, width = 5, height = 3)
```


## B. Principal coordinates analysis of all samples.
```{r}
# import the distance table:
beta = read.table("../data/bray_curtis.txt", header=T, row.names=1, sep="\t", comment.char="") 

design = design[order(design$variety, design$group),]
 
# all the samples were needed.
sub_design = design
idx = rownames(sub_design) %in% rownames(beta)
sub_design=sub_design[idx,]
sub_beta=beta[rownames(sub_design),rownames(sub_design)]
  
# # k is dimension, 3 is recommended; eig is eigenvalues
pcoa = cmdscale(sub_beta, k=4, eig=T) 
# get coordinate string, format to dataframe
points = as.data.frame(pcoa$points) 
eig = pcoa$eig
points = cbind(points, sub_design$group, paste(sub_design$compartment, "_",sub_design$variety, sep = ""))
colnames(points) = c("PC1", "PC2", "PC3", "PC4","group","compartment") 
points$compartment = as.character(points$compartment)
points[points$compartment %in% c("BulkSoil_Bulksoil"),]$compartment= c("BulkSoil")
points[points$compartment %in% c("Rhizosphere_Wildtype"),]$compartment = c("Rs_WT")
points[points$compartment %in% c("Rhizosphere_Mutant"),]$compartment = c("Rs_Mut")
points[points$compartment %in% c("Root_Wildtype"),]$compartment = c("Rt_WT")
points[points$compartment %in% c("Root_Mutant"),]$compartment = c("Rt_Mut")
points$compartment = factor(points$compartment, levels = c("BulkSoil","Rs_WT","Rs_Mut","Rt_WT","Rt_Mut"))
write.table(points, "points_coordinates_for_PCoA.txt",,row.names = T, col.names = T, quote = F, sep = "\t")
# plot PC 1 and 2
p = ggplot(points, aes(x=PC1, y=PC2, color=group, shape = compartment)) + geom_point(alpha=.9, size=2) +
    scale_color_manual(values = c("#60a3bc","#82ccdd","#b71540","#e55039","#e58e26","#fa983a","#f6b93b", "black")) +
    scale_shape_manual(values = c(15,17,4,19,8)) +
    geom_hline(yintercept = 0, linetype="solid", color = "grey") +
    geom_vline(xintercept = 0,linetype="solid", color = "grey") +
    labs(x=paste("PCo 1 (", format(100 * eig[1] / sum(eig), digits=4), "%)", sep=""),
         y=paste("PCo 2 (", format(100 * eig[2] / sum(eig), digits=4), "%)", sep="")) + 
    theme_bw()

if (TRUE){
    p = p + stat_ellipse(level=0.68)
  }
p

ggsave("PCoA_of_all_1B.pdf", p, width = 5, height = 3)

  
```


## C.  Hierarchical clustering based on weighted UniFrac distances between groups
```{r}
# calculate
beta = read.table("../data/weighted_unifrac_group.txt", header = T, row.names = 1, sep = "\t")
  
dist = as.dist(beta)
  
res.hc = hclust(dist, method = "average")
 
p = fviz_dend(res.hc, rect = TRUE, k=4,k_colors = c("black","black","black","black"), ggtheme = theme_bw(),ylab = "Weighted Unifrac distance")# dendrogam
p
ggsave("sample_hclust_1C.pdf", p, width = 10, height = 6)
  


```










